### ISSUE TITLE
能否集成下 LiveRe 评论系统？

### ISSUE THREAD

**Issue by troycizion123** [lengyue1024/lengyue1024.github.io#1]
你好
请问，能否集成下 LiveRe 评论系统？
谢谢

**Comment by lengyue1024** [comment]
可以啊，就是我还没有找到合适的评论系统，您有什么推荐的吗

**Comment by troycizion123** [comment]
最近livere(来必力)很好用的~
畅言需要ICP号码，比较麻烦~^^

**Comment by lengyue1024** [comment]
来必力是挺好的，我也已经注册了，就是这个评论系统我不会安装，因为我用的是改版的next主题，一些配置有点不一样，你可以教教我发自我的华为手机-------- 原始邮件 --------主题：Re: [lengyue1024/lengyue1024.github.io] 能否集成下 LiveRe 评论系统？ (#1)发件人：Troy 收件人："lengyue1024/lengyue1024.github.io" 抄送：lengyue1024 ,Comment 最近livere(来必力)很好用的~
畅言需要ICP号码，比较麻烦~^^

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lengyue1024/lengyue1024.github.io","title":"lengyue1024/lengyue1024.github.io","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/lengyue1024/lengyue1024.github.io"}},"updates":{"snippets":[{"icon":"PERSON","message":"@troycizion123 in #1: 最近livere(来必力)很好用的~\r\n畅言需要ICP号码，比较麻烦~^^"}],"action":{"name":"View Issue","url":"https://github.com/lengyue1024/lengyue1024.github.io/issues/1#issuecomment-369082084"}}}

**Comment by lengyue1024** [comment]
是的发自我的华为手机-------- 原始邮件 --------主题：Re: [lengyue1024/lengyue1024.github.io] 能否集成下 LiveRe 评论系统？ (#1)发件人：Troy 收件人："lengyue1024/lengyue1024.github.io" 抄送：lengyue1024 ,Comment 最近livere(来必力)很好用的~
畅言需要ICP号码，比较麻烦~^^

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lengyue1024/lengyue1024.github.io","title":"lengyue1024/lengyue1024.github.io","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/lengyue1024/lengyue1024.github.io"}},"updates":{"snippets":[{"icon":"PERSON","message":"@troycizion123 in #1: 最近livere(来必力)很好用的~\r\n畅言需要ICP号码，比较麻烦~^^"}],"action":{"name":"View Issue","url":"https://github.com/lengyue1024/lengyue1024.github.io/issues/1#issuecomment-369082084"}}}

**Comment by troycizion123** [comment]
你好，我也不是特别懂这些，我找了几个网上的例子，你看看有没有参考价值吧。

https://blog.smoker.cc/web/add-comments-livere-for-hexo-theme-next.html

https://fxb577328725.github.io/2018/01/27/%E5%88%A9%E7%94%A8Hexo+GitHub%E6%90%AD%E5%BB%BA%E9%9D%99%E6%80%81%E5%8D%9A%E5%AE%A2%E5%B9%B3%E5%8F%B0(%E4%B8%89)-next%E4%B8%BB%E9%A2%98%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8/

**Comment by lengyue1024** [comment]
我目前已经注册了来必力，而且已经经过了很多次尝试了，但是还是不行，我现在已经添加了在线聊天，左下角与右下角分别有一个，你可以直接在那里留言，添加评论的问题等我到学校再解决，还有就是谢谢你的建议，对我的博客有任何建议或者意见，你可以添加我的QQ:3433951572,答案是yue，我都会认真解决的。

发送自 Windows 10 版邮件应用

发件人: Troy
发送时间: 2018年3月2日 15:56
收件人: lengyue1024/lengyue1024.github.io
抄送: lengyue1024; Manual
主题: Re: [lengyue1024/lengyue1024.github.io] 能否集成下 LiveRe 评论系统？ (#1)

你好，我也不是特别懂这些，我找了几个网上的例子，你看看有没有参考价值吧。
https://blog.smoker.cc/web/add-comments-livere-for-hexo-theme-next.html
https://fxb577328725.github.io/2018/01/27/%E5%88%A9%E7%94%A8Hexo+GitHub%E6%90%AD%E5%BB%BA%E9%9D%99%E6%80%81%E5%8D%9A%E5%AE%A2%E5%B9%B3%E5%8F%B0(%E4%B8%89)-next%E4%B8%BB%E9%A2%98%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8/

**Comment by lengyue1024** [comment]
@troycizion123 我已经集成了valine，谢谢你的建议
